/// Flutter icons ProIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProIcons
///      fonts:
///       - asset: fonts/ProIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProIcons {
  ProIcons._();

  static const _kFontFam = 'ProIcons';
  static const String? _kFontPkg = null;

  static const IconData emptyimage_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData config = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emptyimage = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donation = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData found = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partnership = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
